### ISSUE TITLE
2017 Student Involvement and Employment Festival Registration

### ISSUE THREAD

**Issue by 0dd1tty** [0dd1tty/NCSA-Student-Chapter-CSU-Pueblo#10]
If you are interested in participating in the 2017 Student Involvement and Employment Festival being held on Wednesday, August 23, please complete this registration form. Pre-registration is required and space is limited. Chairs are available, but are limited (it is suggested that you bring your own seating.)  You must bring your own materials, additional seating, and tent/covering to ensure your effectiveness and comfort during the festival.  Electricity is limited to those who request it on a first-come, first-served basis.

The deadline to register is Friday, August 7, 2017. Confirmation e-mails will be sent at the end of each month prior to the event.

**Comment by 0dd1tty** [comment]
This needs to be completed by any executive board member. This is set for August 23 and we will need to check out schedules to have someone at the table throughout the day. This will be a great chance to recruit incoming freshman and current students at the campus.

**Comment by jakevigil** [comment]
Sounds neat! My work schedule may not allow me to be there for the entire day, but maybe the executives can split shifts to be at the table.
